### ISSUE TITLE
Deploy contracts to special contract

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-node#49]
The endgame for this is something like:

![Image](https://github.com/user-attachments/assets/f8bbef47-70c0-4993-822f-ed6f00e6843d)

Then the node can check that a contract has been deployed via:
```rust
let mut key = vec![0];
key.extend(contract_addr);
query_state_inclusive_finalized(&conn, &DEPLOY_CONTRACT_ADDR, &key, block_num, solution_index).is_some();
```
So deploying a contract is just creating a solution to the above contract.

**Comment by mitchmindtree** [comment]
Storage layout for the contract deployment contract:

```rust
type Contract {
    salt: b256,
    len: int,
    predicate_addrs: b256[],    
};

type Predicate {
    len_bytes: int,
    bytecode: int[],
};

storage {
    contracts: (b256 => Contract),
    predicates: (b256 => Predicate),
}
```

Query State Keys:

- Get predicate:
    1. `[1, <predicate-address>, 0]` to get the length bytes
    2. `[1, <predicate-address>, 1]` gets the padded words, then truncate to bytes.
- Get contract:
    1. `[0, <contract-address>, 0]` to get the salt (optional).
    2. `[0, <contract-address>, 1]` to get the number of predicates.
    3. `[0, <contract-address>, 2, predicate_addr_ix]` to get the predicate address.


Contract Registry predicate will be an empty slices for state reads and constraints.

Contract Registry address will use salt `sha256("contract registry")`.

Demo solution:

```
Solution {
    predicate_to_solve:  <contract-addr>, <predicate-addr> // from above
    decision_variables: [],
    state_mutations: ..., // A mutation for each key mentioned above.
    transient_data: [],
}
```

## To-Do

- [ ] Add registry contract in big-bang block.
- [ ] Register contract registry in itself.
- [ ] Update DB `get_contract` and `get_predicate` to work in terms of `query_range::finalized`.
