### ISSUE TITLE
Create BigBangBlock type

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-node#52]
Add a big bang block type like:

```rust
pub struct BigBangBlock {
    pub block_state_address: ContentAddress,
    pub contract_registry_address: ContentAddress,
    pub solution: Solution,
}
```

Example YAML:

```yaml
block-state-address: 0x...
contract-registry-address: 0x...
solution: <serialized-solution>
```

## To-Do

- [x] Add the `essential-node-types` crate.
- [x] Add `BigBangBlock` to `essential-node-types`.
- [x] Add default `BigBangBlock` config as `big-bang-block.yml` to repo.
- [x] For now, `include_str!` the `big-bang-block.yml` in `essential-node-types`.
- [x] Add `BigBangBlock` to the node configuration.
- [x] In node run, if no blocks, apply big bang block. This creates and inserts a block at timestamp `0`.
- [x] Add CLI parameter that accepts path to serialized big bang block file in yaml or json.
- [x] Update validation to check block `0` against `BigBangBlock`?
- [ ] RM  old predicate and contract DB interactions. Includes contract, predicate and contract_predicate tables.
- [ ] Change `update_state` sql to use a contract CA directly (rather than ID) or just make it use a key.
- [ ] Expose `&Contract` -> `Vec<Mutation>` fn - from `essential-node-types`?
