### ISSUE TITLE
Node database

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-node#9]
Create local SQLite database using rusqlite for the node. There's no need to implement an in-memory database as well because sqlite has an in-memory option.

## Tasks
- [ ] Set up sqllite as a dependency in our Rust project
- [ ] Choose how to bundle or include the actual sqlite lib
- [ ] Implement rust struct and methods to handle the sql interactions
- [ ] Ensure proper error handling and connection management
- [ ] Write unit tests for database operations
- [ ] Implement a connection pool for efficient database access
- [ ] Document the lib and all functions

## Sql
This can be heavily inspired by the sql in the server but with some differences.
Write the:
- [ ] Create tables
- [ ] Create indices
- [ ] Inserts
- [ ] Updates
- [ ] Reads

### Additional Notes
- Evaluate performance implications and optimize queries or add indices if necessary.

### Resources
- [sqlite documentation](https://www.sqlite.org/)
- [sqlite tutorial](https://www.sqlitetutorial.net/)
- [Rust SQLite](https://github.com/rusqlite/rusqlite)
